name: Integration Tests
on: [push]
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: integration-tests
        uses: schul-cloud/actions-integration-tests
      # upload buils artifacts
      - uses: actions/upload-artifact@v1
        with:
          name: report
          path: reports